### ISSUE TITLE
How expose buildId to server?

### ISSUE THREAD

**Issue by lucasfeliciano** [nexdrew/next-build-id#14]
I'm trying to expose the buildId to the express application so I can set cache keys based on the buildId.

What would be the best way of getting the `buildId`?

**Comment by nexdrew** [comment]
`next-build-id` is just a Node module - you can use it a build time (i.e. when running `next build`) and at runtime (i.e. when running your server via something like `node server.js`), if you want. As long as you use it for the same git repository at the same commit, it will produce a consistent build id (via `git rev-parse HEAD`).

When the module is used at build time (via the `generateBuildId` prop of `next.config.js`), Next stores it on the file system at `$nextAppDir/.next/BUILD_ID`, so if you aren't comfortable using `next-build-id` at runtime, you could potentially read the value out of that file, but that couples your implementation to Next internals, which is probably not a good idea.

Otherwise, you could just call `next-build-id` at runtime when your server starts up, and then you could cache the value in your Express app using `app.locals` (e.g. `app.locals.buildId`), which is then made available to each request via `req.app.locals` (e.g. `req.app.locals.buildId`). At that point, your Express middleware or route handler could simply read it from the request object.

Here's an example, assuming Next app code in a `client` directory and Express server code in a `server` directory, both within the same git repo.

```js
// file: client/build-id.js
// desc: custom module to wrap next-build-id (to encapsulate the `dir` argument)

const nextBuildId = require('next-build-id')

async function generateBuildId () {
  const fromGit = await nextBuildId({ dir: __dirname })
  return fromGit.id
}

module.exports = generateBuildId
```

```js
// file: client/next.config.js
// desc: used at build time via `next build`

const generateBuildId = require('./build-id')

module.exports = {
  generateBuildId
}
```

```js
// file: server/server.js
// desc: express server started at runtime via `node server/server.js`

const path = require('path')
const express = require('express')
const next = require('next')
const generateBuildId = require('../client/build-id')
const nextConfig = require('../client/next.config')

async function main () {
  const nextApp = next({
    dev: process.env.NODE_ENV !== 'production',
    dir: path.resolve(__dirname, '..', 'client'),
    conf: nextConfig
  })
  const nextHandler = nextApp.getRequestHandler()
  await nextApp.prepare()
  const app = express()
  app.locals.buildId = await generateBuildId()

  app.get('/build-id', (req, res) => {
    res.type('text')
    res.send(req.app.locals.buildId)
  })

  app.get('*', (req, res) => {
    return nextHandler(req, res)
  })

  const port = parseInt(process.env.PORT, 10) || 8000
  app.listen(port, err => {
    if (err) throw err
    console.log(`> Ready on http://localhost:${port}`)
  })
}

main()
```

If you want to expose the build id to React client code, then you might need to use a custom `client/pages/_document.js` component that propagates your server value to the browser, like so:

```js
import React from 'react'
import Document, { Head, Main, NextScript } from 'next/document'

export default class extends Document {
  static async getInitialProps (context) {
    const initialProps = await Document.getInitialProps(context)

    let buildId
    if (process.browser) {
      buildId = JSON.parse(document.getElementById('clientConfig').textContent).buildId
    } else {
      buildId = context.req.app.locals.buildId
    }

    return { configValues: { buildId }, ...initialProps }
  }

  render () {
    return (
      <html>
        <Head>
          <script
            id='clientConfig'
            type='application/json'
            dangerouslySetInnerHTML={{
              __html: JSON.stringify(this.props.configValues)
            }}
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

**Comment by lucasfeliciano** [comment]
Thanks for the detailed explanation.

The solution that I found before reading this was reading from the filesystem as you said.

Knowing how `next-build-id` works on runtime/buildtime make things more clear and I liked the `app.locals` solution. It is a perfect fit for my use case.

Thanks :)

**Comment by nexdrew** [comment]
:+1: You're welcome, glad it works for you!
