### ISSUE TITLE
Expose current git tag to return result

### ISSUE THREAD

**Issue by minhluong96** [nexdrew/next-build-id#16]
I need to take the current git tag in my project. Could you take a look at this [pull request #15](https://github.com/nexdrew/next-build-id/pull/15)?

**Comment by nexdrew** [comment]
@minhluong96 Hi!

This library was a bit dated and needed an overhaul to drop support for older versions of Next.js and make it easier to use for modern versions - so I took the opportunity to implement your idea as well.

I recently published pre-release version `3.0.0-rc1` (under the `rc` distribution tag) to npm.

```console
$ npm i next-build-id@rc
```

It now supports a `describe: true` option that will use `git describe --tags` instead of `git rev-parse HEAD`. The library will also now resolve to a string instead of an object.

Here's an example:

```js
// next.config.js
const nextBuildId = require('next-build-id')
module.exports = {
  generateBuildId: () => nextBuildId({ dir: __dirname, describe: true })
}
// => 'v1.0.0' (no changes since v1.0.0 tag)
// => 'v1.0.0-19-ga8f7eee' (19 changes since v1.0.0 tag)
```

If no tags exist in the local git repository, it will fallback to the latest commit sha (same as if `describe: true` were not given).

A preview of the new README can be found here: https://www.npmjs.com/package/next-build-id/v/3.0.0-rc1

Please give it a shot when you get a chance and let me know if it works for you.

**Comment by nexdrew** [comment]
@minhluong96 Have you had a chance to give `next-build-id@3.0.0-rc1` a try yet? When you do, please let me know. Thanks!

**Comment by vitorhsb** [comment]
@nexdrew , it looks good to me. I also have this requirement to use git tags and it worked out.

**Comment by nexdrew** [comment]
@vitorhsb Thanks! Now I just need to update the tests in my `overhaul` branch, and then I will open/merge a PR and release version 3.0.0. In the meantime, feel free to continue using version 3.0.0-rc1 - it will always be available.

**Comment by nexdrew** [comment]
@minhluong96 @vitorhsb Just posting an update here that `next-build-id@3.0.0` has finally been published, so you don't need to use the rc version anymore.

The [example code posted above](https://github.com/nexdrew/next-build-id/issues/16#issuecomment-496570918) should work exactly the same.

Thanks for contributing, and thanks for using `next-build-id`!
