### ISSUE TITLE
Add synchronous version of plugin

### ISSUE THREAD

**Issue by sheerun** [nexdrew/next-build-id#17]
Would it be possible to get synchronous version of this plugin? It would be useful e.g. for passing buildId directly to Sentry configuration in custom server implementation.

**Comment by nexdrew** [comment]
Sounds reasonable.

Looking at the code now, I think even the async version is due for some improvements. Perhaps I can start rewriting the code to use `async`/`await` to prepare for dropping Node 6 (which is EOL at the end of this month) and include a sync version with it.

Unless you beat me to it, that is. 😺

**Comment by nexdrew** [comment]
I think it's time to overhaul this library. I'd like to make the following changes as a major version bump (v3):

- Remove the hacky file overwriting (essentially dropping support for Next versions below 6)
- Drop the `next-build-id` CLI (preferred usage is now as a library within your **next.config.js** config file/module)
- Drop Node 6 support, start using `async`/`await`
- Modify the library's primary API to return (resolve to) a string (the build id), rather than an object, to make it more convenient as the `generateBuildId` impl
- Add a sync version of the API to address this issue
- Add an option to use `git describe --tags` (instead of `git rev-parse HEAD`), to address issue #16
- Update tests to use only modern versions of Next (6, 7, 8)
- Update README/docs accordingly

I plan on tackling this sometime within the next week.

@sheerun @minhluong96 Thanks for the ideas! Let me know if you have any others.

**Comment by sheerun** [comment]
Sounds great :) If I can throw one more idea then please don't use git at all but rather read directly from .git directory, it's not that hard:

1. read `.git/HEAD` to find out ref, the result is something like `ref: refs/heads/master`
2. read this file to find our current commit (e.g. `.git/refs/heads/master`)

This way is much faster, more reliable (no spawning) and drops `git` binary dependency

**Comment by nexdrew** [comment]
Ok. I'm not crazy about relying on "git internals" but this sounds safe/reasonable enough. I'll give it a try. Thanks!

**Comment by nexdrew** [comment]
@sheerun I recently published version `3.0.0-rc1` (under the `rc` distribution tag) to npm.

```console
$ npm i next-build-id@rc
```

It now contains a synchronous version that returns the latest commit sha as a string. It also uses your suggestion of reading it directly from the file system (by default) instead of spawning a child process to call `git`.

```js
const nextBuildId = require('next-build-id')
const id = nextBuildId.sync({ dir: __dirname })
// => '935cd3f6ff53e4dac7f036d3ca2517e07269bf45'
```

Preview of new README can be found here: https://www.npmjs.com/package/next-build-id/v/3.0.0-rc1

Please give it a shot when you get a chance and let me know if it works for you.

**Comment by sheerun** [comment]
Thank you :) Why not make it sync by default? It's major semver bump

**Comment by nexdrew** [comment]
I thought about that, but I'm just not comfortable making things (like file system access) synchronous (as the only option) when they _should_ be asynchronous - from my days working on yargs, I learned the hard way that trying to keep things synchronous can severely limit what a library is capable of. (This is one of the main reasons I wrote [sywac](https://github.com/sywac/sywac) as an async alternative to yargs.)

I don't have a problem offering a synchronous version as an option when it's possible, similar to the Node API itself, but I don't want to make it the default.

**Comment by nexdrew** [comment]
@sheerun Were you able to test with `next-build-id@3.0.0-rc1`? Does it satisfy your use-case?

**Comment by sheerun** [comment]
I works good

**Comment by nexdrew** [comment]
Ok great, thanks!

**Comment by nexdrew** [comment]
FYI, `next-build-id@3.0.0` has finally been published and it contains a `sync` version [as mentioned above](https://github.com/nexdrew/next-build-id/issues/17#issuecomment-496567474).

Thanks for the suggestion! Let me know if you have any problems or other suggestions. ❤️
